openapi: 3.0.0
info:
  title: 'Invoice processing API'
  description: 'API for managing sales invoices'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000/api'
    description: 'API Server'
paths:
  /sales-invoices:
    post:
      tags:
        - Invoices
      summary: 'Upload a new sales invoice'
      description: 'Creates a new sales invoice with customer details and line items'
      operationId: df3843551885fadc31c63ab14a01c8d6
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - customer_name
                - invoice_date
                - total_amount
                - invoice_lines
              properties:
                customer_name:
                  description: 'Name of the customer'
                  type: string
                  maxLength: 255
                  example: 'Kaiyu Company'
                invoice_date:
                  description: 'Date of the invoice'
                  type: string
                  format: date
                  example: '2024-01-15'
                total_amount:
                  description: 'Total amount of the invoice'
                  type: number
                  format: float
                  minimum: 0
                  example: 1500
                invoice_lines:
                  description: 'Array of invoice line items'
                  type: array
                  items: { required: [description, quantity, unit_price, amount], properties: { description: { description: 'Description of the line item', type: string, maxLength: 1000, example: 'Web Development Services' }, quantity: { description: 'Quantity of the item', type: number, format: float, minimum: 0, example: 10 }, unit_price: { description: 'Unit price of the item', type: number, format: float, minimum: 0, example: 100 }, amount: { description: 'Total amount for this line', type: number, format: float, minimum: 0, example: 1000 } }, type: object }
                  minItems: 1
              type: object
      responses:
        '201':
          description: 'Invoice created successfully'
          content:
            application/json:
              schema:
                properties:
                  status: { description: "Result of sending invoice to ExactOnline. If it is sent successfully, the status is 'success'. Otherwise, the status is 'incomplete'.", type: string, enum: [success, incomplete], example: success }
                  message: { type: string, example: 'Invoice uploaded successfully, and has been sent to ExactOnline' }
                  invoice: { properties: { id: { type: integer, example: 1 }, customer_name: { type: string, example: 'Test Customer Integration' }, invoice_date: { type: string, format: date, example: '2024-01-15' }, total_amount: { type: number, format: float, example: 1500 }, created_at: { type: string, format: date-time }, updated_at: { type: string, format: date-time }, invoice_lines: { type: array, items: { properties: { id: { type: integer, example: 1 }, sales_invoice_id: { type: integer, example: 1 }, description: { type: string, example: 'Web Development Services' }, quantity: { type: number, format: float, example: 10 }, unit_price: { type: number, format: float, example: 100 }, amount: { type: number, format: float, example: 1000 }, created_at: { type: string, format: date-time }, updated_at: { type: string, format: date-time } }, type: object } } }, type: object }
                type: object
        '401':
          description: 'Authentication error.'
          content:
            application/json:
              schema:
                properties:
                  message: { type: string, example: 'Need authentication to access this endpoint' }
                type: object
        '422':
          description: 'Validation error.'
          content:
            application/json:
              schema:
                properties:
                  message: { type: string, example: 'The given data was invalid.' }
                  errors: { properties: { customer_name: { type: array, items: { type: string, example: 'Customer name is required.' } } }, type: object }
                type: object
tags:
  -
    name: Invoices
    description: Invoices
