openapi: 3.0.0
info:
  title: 'Invoice processing API'
  description: 'API for managing sales invoices'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000/api'
    description: 'API Server'
paths:
  /api/sales-invoices:
    post:
      tags:
        - Invoices
      summary: 'Upload a new sales invoice'
      description: 'Creates a new sales invoice with customer details and line items'
      operationId: a2cd58b97fe837161c50332d36e158b4
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - customerName
                - invoiceDate
                - totalAmount
                - invoiceLines
              properties:
                customerName:
                  description: 'Name of the customer'
                  type: string
                  maxLength: 255
                  example: 'Kaiyu Company'
                invoiceDate:
                  description: 'Date of the invoice'
                  type: string
                  format: date
                  example: '2024-01-15'
                totalAmount:
                  description: 'Total amount of the invoice'
                  type: number
                  format: float
                  minimum: 0
                  example: 1500
                invoiceLines:
                  description: 'Array of invoice line items'
                  type: array
                  items: { required: [description, quantity, unitPrice, amount], properties: { description: { description: 'Description of the line item', type: string, maxLength: 1000, example: 'Web Development Services' }, quantity: { description: 'Quantity of the item', type: number, format: float, minimum: 0, example: 10 }, unitPrice: { description: 'Unit price of the item', type: number, format: float, minimum: 0, example: 100 }, amount: { description: 'Total amount for this line', type: number, format: float, minimum: 0, example: 1000 } }, type: object }
                  minItems: 1
              type: object
      responses:
        '201':
          description: 'Invoice created successfully'
          content:
            application/json:
              schema:
                properties:
                  message: { type: string, example: 'Invoice uploaded successfully' }
                  invoice: { properties: { id: { type: integer, example: 1 }, customerName: { type: string, example: 'John Doe Company' }, invoiceDate: { type: string, format: date, example: '2024-01-15' }, totalAmount: { type: number, format: float, example: 1500 }, created_at: { type: string, format: date-time }, updated_at: { type: string, format: date-time }, invoice_lines: { type: array, items: { properties: { id: { type: integer, example: 1 }, description: { type: string, example: 'Web Development Services' }, quantity: { type: number, format: float, example: 10 }, unitPrice: { type: number, format: float, example: 100 }, amount: { type: number, format: float, example: 1000 } }, type: object } } }, type: object }
                type: object
        '422':
          description: 'Validation error'
          content:
            application/json:
              schema:
                properties:
                  message: { type: string, example: 'The given data was invalid.' }
                  errors: { properties: { customerName: { type: array, items: { type: string, example: 'Customer name is required.' } } }, type: object }
                type: object
tags:
  -
    name: Invoices
    description: Invoices
